apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-webserver
  labels:
    app: sample-webserver
spec:
  replicas: {{ .Values.application.replicas }}
  selector:
    matchLabels:
      app: sample-webserver
  template:
    metadata:
      labels:
        app: sample-webserver
    spec:
      hostname: sample-webserver-{{ .Values.application.version }}
      containers:
      - name: sample-webserver
        image: registry.k8s.io/e2e-test-images/agnhost:2.40
        args:
        - serve-hostname
        - --port 
        - "8080"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3